;;; ejc-keywords.el -- list of db-specific keywords (the part of ejc-sql).

;;; Copyright © 2019 - Kostafey <kostafey@gmail.com>

;;; This program is free software; you can redistribute it and/or modify
;;; it under the terms of the GNU General Public License as published by
;;; the Free Software Foundation; either version 2, or (at your option)
;;; any later version.
;;;
;;; This program is distributed in the hope that it will be useful,
;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;; GNU General Public License for more details.
;;;
;;; You should have received a copy of the GNU General Public License
;;; along with this program; if not, write to the Free Software Foundation,
;;; Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.  */

;;; Code:

(require 'ejc-doc)

;;;###autoload
(cl-defun ejc-get-db-keywords (product &optional version)
  (let* ((dbs
          (list
           'mysql
           (list
            "5.5"
            (list
             "ACCESSIBLE" "ACTION" "ADD" "AFTER" "AGAINST" "AGGREGATE"
             "ALGORITHM" "ALL" "ALTER" "ANALYZE" "AND" "ANY" "AS" "ASC" "ASCII"
             "ASENSITIVE" "AT" "AUTHORS" "AUTOEXTEND_SIZE" "AUTO_INCREMENT" "AVG"
             "AVG_ROW_LENGTH" "BACKUP" "BEFORE" "BEGIN" "BETWEEN" "BIGINT" "BINARY"
             "BINLOG" "BIT" "BLOB" "BLOCK" "BOOL" "BOOLEAN" "BOTH" "BTREE" "BY" "BYTE"
             "CACHE" "CALL" "CASCADE" "CASCADED" "CASE" "CATALOG_NAME" "CHAIN" "CHANGE"
             "CHANGED" "CHAR" "CHARACTER" "CHARSET" "CHECK" "CHECKSUM" "CIPHER"
             "CLASS_ORIGIN" "CLIENT" "CLOSE" "COALESCE" "CODE" "COLLATE" "COLLATION"
             "COLUMN" "COLUMNS" "COLUMN_NAME" "COMMENT" "COMMIT" "COMMITTED" "COMPACT"
             "COMPLETION" "COMPRESSED" "CONCURRENT" "CONDITION" "CONNECTION" "CONSISTENT"
             "CONSTRAINT" "CONSTRAINT_CATALOG" "CONSTRAINT_NAME" "CONSTRAINT_SCHEMA"
             "CONTAINS" "CONTEXT" "CONTINUE" "CONTRIBUTORS" "CONVERT" "CPU" "CREATE"
             "CROSS" "CUBE" "CURRENT_DATE" "CURRENT_TIME" "CURRENT_TIMESTAMP"
             "CURRENT_USER" "CURSOR" "CURSOR_NAME" "DATA" "DATABASE" "DATABASES" "DATAFILE"
             "DATE" "DATETIME" "DAY" "DAY_HOUR" "DAY_MICROSECOND" "DAY_MINUTE" "DAY_SECOND"
             "DEALLOCATE" "DEC" "DECIMAL" "DECLARE" "DEFAULT" "DEFINER" "DELAYED"
             "DELAY_KEY_WRITE" "DELETE" "DESC" "DESCRIBE" "DES_KEY_FILE" "DETERMINISTIC"
             "DIRECTORY" "DISABLE" "DISCARD" "DISK" "DISTINCT" "DISTINCTROW" "DIV" "DO"
             "DOUBLE" "DROP" "DUAL" "DUMPFILE" "DUPLICATE" "DYNAMIC" "EACH" "ELSE" "ELSEIF"
             "ENABLE" "ENCLOSED" "END" "ENDS" "ENGINE" "ENGINES" "ENUM" "ERROR" "ERRORS"
             "ESCAPE" "ESCAPED" "EVENT" "EVENTS" "EVERY" "EXECUTE" "EXISTS" "EXIT"
             "EXPANSION" "EXPLAIN" "EXTENDED" "EXTENT_SIZE" "FALSE" "FAST" "FAULTS" "FETCH"
             "FIELDS" "FILE" "FIRST" "FIXED" "FLOAT" "FLOAT4" "FLOAT8" "FLUSH" "FOR"
             "FORCE" "FOREIGN" "FOUND" "FRAC_SECOND" "FROM" "FULL" "FULLTEXT" "FUNCTION"
             "GENERAL" "GEOMETRY" "GEOMETRYCOLLECTION" "GET_FORMAT" "GLOBAL" "GRANT"
             "GRANTS" "GROUP" "HANDLER" "HASH" "HAVING" "HELP" "HIGH_PRIORITY" "HOST"
             "HOSTS" "HOUR" "HOUR_MICROSECOND" "HOUR_MINUTE" "HOUR_SECOND" "IDENTIFIED"
             "IF" "IGNORE" "IGNORE_SERVER_IDS" "IMPORT" "IN" "INDEX" "INDEXES" "INFILE"
             "INITIAL_SIZE" "INNER" "INNOBASE" "INNODB" "INOUT" "INSENSITIVE" "INSERT"
             "INSERT_METHOD" "INSTALL" "INT" "INT1" "INT2" "INT3" "INT4" "INT8" "INTEGER"
             "INTERVAL" "INTO" "INVOKER" "IO" "IO_THREAD" "IPC" "IS" "ISOLATION" "ISSUER"
             "ITERATE" "JOIN" "KEY" "KEYS" "KEY_BLOCK_SIZE" "KILL" "LANGUAGE" "LAST"
             "LEADING" "LEAVE" "LEAVES" "LEFT" "LESS" "LEVEL" "LIKE" "LIMIT" "LINEAR"
             "LINES" "LINESTRING" "LIST" "LOAD" "LOCAL" "LOCALTIME" "LOCALTIMESTAMP" "LOCK"
             "LOCKS" "LOGFILE" "LOGS" "LONG" "LONGBLOB" "LONGTEXT" "LOOP" "LOW_PRIORITY"
             "MASTER" "MASTER_CONNECT_RETRY" "MASTER_HEARTBEAT_PERIOD" "MASTER_HOST"
             "MASTER_LOG_FILE" "MASTER_LOG_POS" "MASTER_PASSWORD" "MASTER_PORT"
             "MASTER_SERVER_ID" "MASTER_SSL" "MASTER_SSL_CA" "MASTER_SSL_CAPATH"
             "MASTER_SSL_CERT" "MASTER_SSL_CIPHER" "MASTER_SSL_KEY"
             "MASTER_SSL_VERIFY_SERVER_CERT" "MASTER_USER" "MATCH" "MAXVALUE"
             "MAX_CONNECTIONS_PER_HOUR" "MAX_QUERIES_PER_HOUR" "MAX_ROWS" "MAX_SIZE"
             "MAX_UPDATES_PER_HOUR" "MAX_USER_CONNECTIONS" "MEDIUM" "MEDIUMBLOB"
             "MEDIUMINT" "MEDIUMTEXT" "MEMORY" "MERGE" "MESSAGE_TEXT" "MICROSECOND"
             "MIDDLEINT" "MIGRATE" "MINUTE" "MINUTE_MICROSECOND" "MINUTE_SECOND" "MIN_ROWS"
             "MOD" "MODE" "MODIFIES" "MODIFY" "MONTH" "MULTILINESTRING" "MULTIPOINT"
             "MULTIPOLYGON" "MUTEX" "MYSQL_ERRNO" "NAME" "NAMES" "NATIONAL" "NATURAL"
             "NCHAR" "NDB" "NDBCLUSTER" "NEW" "NEXT" "NO" "NODEGROUP" "NONE" "NOT"
             "NO_WAIT" "NO_WRITE_TO_BINLOG" "NULL" "NUMERIC" "NVARCHAR" "OFFSET"
             "OLD_PASSWORD" "ON" "ONE" "ONE_SHOT" "OPEN" "OPTIMIZE" "OPTION" "OPTIONALLY"
             "OPTIONS" "OR" "ORDER" "OUT" "OUTER" "OUTFILE" "OWNER" "PACK_KEYS" "PAGE"
             "PARSER" "PARTIAL" "PARTITION" "PARTITIONING" "PARTITIONS" "PASSWORD" "PHASE"
             "PLUGIN" "PLUGINS" "POINT" "POLYGON" "PORT" "PRECISION" "PREPARE" "PRESERVE"
             "PREV" "PRIMARY" "PRIVILEGES" "PROCEDURE" "PROCESSLIST" "PROFILE" "PROFILES"
             "PROXY" "PURGE" "QUARTER" "QUERY" "QUICK" "RANGE" "READ" "READS" "READ_ONLY"
             "READ_WRITE" "REAL" "REBUILD" "RECOVER" "REDOFILE" "REDO_BUFFER_SIZE"
             "REDUNDANT" "REFERENCES" "REGEXP" "RELAY" "RELAYLOG" "RELAY_LOG_FILE"
             "RELAY_LOG_POS" "RELAY_THREAD" "RELEASE" "RELOAD" "REMOVE" "RENAME"
             "REORGANIZE" "REPAIR" "REPEAT" "REPEATABLE" "REPLACE" "REPLICATION" "REQUIRE"
             "RESET" "RESIGNAL" "RESTORE" "RESTRICT" "RESUME" "RETURN" "RETURNS" "REVOKE"
             "RIGHT" "RLIKE" "ROLLBACK" "ROLLUP" "ROUTINE" "ROW" "ROWS" "ROW_FORMAT"
             "RTREE" "SAVEPOINT" "SCHEDULE" "SCHEMA" "SCHEMAS" "SCHEMA_NAME" "SECOND"
             "SECOND_MICROSECOND" "SECURITY" "SELECT" "SENSITIVE" "SEPARATOR" "SERIAL"
             "SERIALIZABLE" "SERVER" "SESSION" "SET" "SHARE" "SHOW" "SHUTDOWN" "SIGNAL"
             "SIGNED" "SIMPLE" "SLAVE" "SLOW" "SMALLINT" "SNAPSHOT" "SOCKET" "SOME"
             "SONAME" "SOUNDS" "SOURCE" "SPATIAL" "SPECIFIC" "SQL" "SQLEXCEPTION"
             "SQLSTATE" "SQLWARNING" "SQL_BIG_RESULT" "SQL_BUFFER_RESULT" "SQL_CACHE"
             "SQL_CALC_FOUND_ROWS" "SQL_NO_CACHE" "SQL_SMALL_RESULT" "SQL_THREAD"
             "SQL_TSI_DAY" "SQL_TSI_FRAC_SECOND" "SQL_TSI_HOUR" "SQL_TSI_MINUTE"
             "SQL_TSI_MONTH" "SQL_TSI_QUARTER" "SQL_TSI_SECOND" "SQL_TSI_WEEK"
             "SQL_TSI_YEAR" "SSL" "START" "STARTING" "STARTS" "STATUS" "STOP" "STORAGE"
             "STRAIGHT_JOIN" "STRING" "SUBCLASS_ORIGIN" "SUBJECT" "SUBPARTITION"
             "SUBPARTITIONS" "SUPER" "SUSPEND" "SWAPS" "SWITCHES" "TABLE" "TABLES"
             "TABLESPACE" "TABLE_CHECKSUM" "TABLE_NAME" "TEMPORARY" "TEMPTABLE"
             "TERMINATED" "TEXT" "THAN" "THEN" "TIME" "TIMESTAMP" "TIMESTAMPADD"
             "TIMESTAMPDIFF" "TINYBLOB" "TINYINT" "TINYTEXT" "TO" "TRAILING" "TRANSACTION"
             "TRIGGER" "TRIGGERS" "TRUE" "TRUNCATE" "TYPE" "TYPES" "UNCOMMITTED"
             "UNDEFINED" "UNDO" "UNDOFILE" "UNDO_BUFFER_SIZE" "UNICODE" "UNINSTALL" "UNION"
             "UNIQUE" "UNKNOWN" "UNLOCK" "UNSIGNED" "UNTIL" "UPDATE" "UPGRADE" "USAGE"
             "USE" "USER" "USER_RESOURCES" "USE_FRM" "USING" "UTC_DATE" "UTC_TIME"
             "UTC_TIMESTAMP" "VALUE" "VALUES" "VARBINARY" "VARCHAR" "VARCHARACTER"
             "VARIABLES" "VARYING" "VIEW" "WAIT" "WARNINGS" "WEEK" "WHEN" "WHERE" "WHILE"
             "WITH" "WORK" "WRAPPER" "WRITE" "X509" "XA" "XML" "XOR" "YEAR" "YEAR_MONTH"
             "ZEROFILL" 
             ;; MySQL 5.5 New Keywords and Reserved Words
             "CATALOG_NAME" "CLASS_ORIGIN" "COLUMN_NAME" "CONSTRAINT_CATALOG"
             "CONSTRAINT_NAME" "CONSTRAINT_SCHEMA" "CURSOR_NAME" "ERROR" "GENERAL"
             "IGNORE_SERVER_IDS" "MASTER_HEARTBEAT_PERIOD" "MESSAGE_TEXT" "MYSQL_ERRNO"
             "PROXY" "RELAY" "RELAYLOG" "RESIGNAL" "SCHEMA_NAME" "SIGNAL" "SLOW"
             "SUBCLASS_ORIGIN" "TABLE_NAME" "XML")
            "5.6" '()
            "5.7" '()
            "8.0" '())))
         (db (plist-get dbs product)))
    (if version (plist-get version db)
      (cadr db))))

(defconst ejc-mysql-doc (make-hash-table :test 'eq))

(ejc-fill-doc
 ejc-mysql-doc
 'ABS	"Return the absolute value"
 'ACOS	"Return the arc cosine"
 'ADDDATE	"Add time values (intervals) to a date value"
 'ADDTIME	"Add time"
 'AES_DECRYPT	"Decrypt using AES"
 'AES_ENCRYPT	"Encrypt using AES"
 'AND	"Logical AND"
 '&&	"Logical AND"
 'Area	"Return Polygon or MultiPolygon area"
 'AsBinary	"Convert from internal geometry format to WKB"
 'AsWKB	"Convert from internal geometry format to WKB"
 'ASCII	"Return numeric value of left-most character"
 'ASIN	"Return the arc sine"
 '=	"Assign a value (as part of a SET statement, or as part of the SET clause in an UPDATE statement)"
 ':=	"Assign a value"
 'AsText	"Convert from internal geometry format to WKT"
 'AsWKT	"Convert from internal geometry format to WKT"
 'ATAN	"Return the arc tangent"
 'ATAN2	"Return the arc tangent of the two arguments"
 'ATAN	"Return the arc tangent of the two arguments"
 'AVG	"Return the average value of the argument"
 'BENCHMARK	"Repeatedly execute an expression"
 'BETWEEN	"Check whether a value is within a range of values"
 'BIN	"Return a string containing binary representation of a number"
 'BINARY	"Cast a string to a binary string"
 'BIT_AND	"Return bitwise AND"
 'BIT_COUNT	"Return the number of bits that are set"
 'BIT_LENGTH	"Return length of argument in bits"
 'BIT_OR	"Return bitwise OR"
 'BIT_XOR	"Return bitwise XOR"
 '&	"Bitwise AND"
 '~	"Bitwise inversion"
 '|	"Bitwise OR"
 '^	"Bitwise XOR"
 'CASE	"Case operator"
 'CAST	"Cast a value as a certain type"
 'CEIL	"Return the smallest integer value not less than the argument"
 'CEILING	"Return the smallest integer value not less than the argument"
 'Centroid	"Return centroid as a point"
 'CHAR	"Return the character for each integer passed"
 'CHAR_LENGTH	"Return number of characters in argument"
 'CHARACTER_LENGTH	"Synonym for CHAR_LENGTH"
 'CHARSET	"Return the character set of the argument"
 'COALESCE	"Return the first non-NULL argument"
 'COERCIBILITY	"Return the collation coercibility value of the string argument"
 'COLLATION	"Return the collation of the string argument"
 'COMPRESS	"Return result as a binary string"
 'CONCAT	"Return concatenated string"
 'CONCAT_WS	"Return concatenate with separator"
 'CONNECTION_ID	"Return the connection ID (thread ID) for the connection"
 'Contains	"Whether MBR of one geometry contains MBR of another"
 'CONV	"Convert numbers between different number bases"
 'CONVERT	"Cast a value as a certain type"
 'CONVERT_TZ	"Convert from one time zone to another"
 'COS	"Return the cosine"
 'COT	"Return the cotangent"
 'COUNT	"Return a count of the number of rows returned" 
 'CRC32	"Compute a cyclic redundancy check value"
 'Crosses	"Whether one geometry crosses another"
 'CURDATE	"Return the current date"
 'CURRENT_DATE	"Synonyms for CURDATE"
 'CURRENT_TIME	"Synonyms for CURTIME"
 'CURRENT_TIMESTAMP	"Synonyms for NOW"
 'CURRENT_USER	"The authenticated user name and host name"
 'CURTIME	"Return the current time"
 'DATABASE	"Return the default (current) database name"
 'DATE	"Extract the date part of a date or datetime expression"
 'DATE_ADD	"Add time values (intervals) to a date value"
 'DATE_FORMAT	"Format date as specified"
 'DATE_SUB	"Subtract a time value (interval) from a date"
 'DATEDIFF	"Subtract two dates"
 'DAY	"Synonym for DAYOFMONTH"
 'DAYNAME	"Return the name of the weekday"
 'DAYOFMONTH	"Return the day of the month (0-31)"
 'DAYOFWEEK	"Return the weekday index of the argument"
 'DAYOFYEAR	"Return the day of the year (1-366)"
 'DECODE	"Decodes a string encrypted using ENCODE"
 'DEFAULT	"Return the default value for a table column"
 'DEGREES	"Convert radians to degrees"
 'DES_DECRYPT	"Decrypt a string"
 'DES_ENCRYPT	"Encrypt a string"
 'Dimension	"Dimension of geometry"
 'Disjoint	"Whether MBRs of two geometries are disjoint"
 'DIV	"Integer division"
 '/	"Division operator"
 'ELT	"Return string at index number"
 'ENCODE	"Encode a string"
 'ENCRYPT	"Encrypt a string"
 'EndPoint	"End Point of LineString"
 'Envelope	"Return MBR of geometry"
 '=	"Equal operator"
 '<=>	"NULL-safe equal to operator"
 'Equals	"Whether MBRs of two geometries are equal"
 'EXP	"Raise to the power of"
 'EXPORT_SET	"Return a string such that for every bit set in the value bits, you get an on string and for every unset bit, you get an off string"
 'ExteriorRing	"Return exterior ring of Polygon"
 'EXTRACT	"Extract part of a date"
 'ExtractValue	"Extracts a value from an XML string using XPath notation"
 'FIELD	"Return the index (position) of the first argument in the subsequent arguments"
 'FIND_IN_SET	"Return the index position of the first argument within the second argument"
 'FLOOR	"Return the largest integer value not greater than the argument"
 'FORMAT	"Return a number formatted to specified number of decimal places"
 'FOUND_ROWS	"For a SELECT with a LIMIT clause, the number of rows that would be returned were there no LIMIT clause"
 'FROM_DAYS	"Convert a day number to a date"
 'FROM_UNIXTIME	"Format Unix timestamp as a date"
 'GeomCollFromText	"Return geometry collection from WKT"
 'GeometryCollectionFromText	"Return geometry collection from WKT"
 'GeomCollFromWKB	"Return geometry collection from WKB"
 'GeometryCollectionFromWKB	"Return geometry collection from WKB"
 'GeometryCollection	"Construct geometry collection from geometries"
 'GeometryN	"Return N-th geometry from geometry collection"
 'GeometryType	"Return name of geometry type"
 'GeomFromText	"Return geometry from WKT"
 'GeometryFromText	"Return geometry from WKT"
 'GeomFromWKB	"Return geometry from WKB"
 'GeometryFromWKB	"Return geometry from WKB"
 'GET_FORMAT	"Return a date format string"
 'GET_LOCK	"Get a named lock"
 'GLength	"Return length of LineString"
 '>	"Greater than operator"
 '>=	"Greater than or equal operator"
 'GREATEST	"Return the largest argument"
 'GROUP_CONCAT	"Return a concatenated string"
 'HEX	"Return a hexadecimal representation of a decimal or string value"
 'HOUR	"Extract the hour"
 'IF	"If/else construct"
 'IFNULL	"Null if/else construct"
 'IN	"Check whether a value is within a set of values"
 'INET_ATON	"Return the numeric value of an IP address"
 'INET_NTOA	"Return the IP address from a numeric value"
 'INSERT	"Insert a substring at the specified position up to the specified number of characters"
 'INSTR	"Return the index of the first occurrence of substring"
 'InteriorRingN	"Return N-th interior ring of Polygon"
 'Intersects	"Whether MBRs of two geometries intersect"
 'INTERVAL	"Return the index of the argument that is less than the first argument"
 'IS	"Test a value against a boolean"
 'IS_FREE_LOCK	"Whether the named lock is free"
 'IS_USED_LOCK	"Whether the named lock is in use; return connection identifier if true"
 'IsClosed	"Whether a geometry is closed and simple"
 'IsEmpty	"Placeholder function"
 'ISNULL	"Test whether the argument is NULL"
 'IsSimple	"Whether a geometry is simple"
 'LAST_DAY	"Return the last day of the month for the argument"
 'LAST_INSERT_ID	"Value of the AUTOINCREMENT column for the last INSERT"
 'LCASE	"Synonym for LOWER"
 'LEAST	"Return the smallest argument"
 'LEFT	"Return the leftmost number of characters as specified"
 '<<	"Left shift"
 'LENGTH	"Return the length of a string in bytes"
 '<	"Less than operator"
 '<=	"Less than or equal operator"
 'LIKE	"Simple pattern matching"
 'LineFromText	"Construct LineString from WKT"
 'LineStringFromText	"Construct LineString from WKT"
 'LineFromWKB	"Construct LineString from WKB"
 'LineStringFromWKB	"Construct LineString from WKB"
 'LineString	"Construct LineString from Point values"
 'LN	"Return the natural logarithm of the argument"
 'LOAD_FILE	"Load the named file"
 'LOCALTIME	"Synonym for NOW"
 'LOCALTIMESTAMP	"Synonym for NOW"
 'LOCATE	"Return the position of the first occurrence of substring"
 'LOG	"Return the natural logarithm of the first argument"
 'LOG10	"Return the base-10 logarithm of the argument"
 'LOG2	"Return the base-2 logarithm of the argument"
 'LOWER	"Return the argument in lowercase"
 'LPAD	"Return the string argument, left-padded with the specified string"
 'LTRIM	"Remove leading spaces"
 'MAKE_SET	"Return a set of comma-separated strings that have the corresponding bit in bits set"
 'MAKEDATE	"Create a date from the year and day of year"
 'MAKETIME	"Create time from hour, minute, second"
 'MASTER_POS_WAIT	"Block until the slave has read and applied all updates up to the specified position"
 'MATCH	"Perform full-text search"
 'MAX	"Return the maximum value"
 'MBRContains	"Whether MBR of one geometry contains MBR of another"
 'MBRDisjoint	"Whether MBRs of two geometries are disjoint"
 'MBREqual	"Whether MBRs of two geometries are equal"
 'MBRIntersects	"Whether MBRs of two geometries intersect"
 'MBROverlaps	"Whether MBRs of two geometries overlap"
 'MBRTouches	"Whether MBRs of two geometries touch"
 'MBRWithin	"Whether MBR of one geometry is within MBR of another"
 'MD5	"Calculate MD5 checksum"
 'MICROSECOND	"Return the microseconds from argument"
 'MID	"Return a substring starting from the specified position"
 'MIN	"Return the minimum value"
 '-	"Minus operator"
 'MINUTE	"Return the minute from the argument"
 'MLineFromText	"Construct MultiLineString from WKT"
 'MultiLineStringFromText	"Construct MultiLineString from WKT"
 'MLineFromWKB	"Construct MultiLineString from WKB"
 'MultiLineStringFromWKB	"Construct MultiLineString from WKB"
 'MOD	"Return the remainder"
 '%
 'MONTH	"Return the month from the date passed"
 'MONTHNAME	"Return the name of the month"
 'MPointFromText	"Construct MultiPoint from WKT"
 'MultiPointFromText	"Construct MultiPoint from WKT"
 'MPointFromWKB	"Construct MultiPoint from WKB"
 'MultiPointFromWKB	"Construct MultiPoint from WKB"
 'MPolyFromText	"Construct MultiPolygon from WKT"
 'MultiPolygonFromText	"Construct MultiPolygon from WKT"
 'MPolyFromWKB	"Construct MultiPolygon from WKB"
 'MultiPolygonFromWKB	"Construct MultiPolygon from WKB"
 'MultiLineString	"Contruct MultiLineString from LineString values"
 'MultiPoint	"Construct MultiPoint from Point values"
 'MultiPolygon	"Construct MultiPolygon from Polygon values"
 'NAME_CONST	"Causes the column to have the given name"
 'NOT	"Negates value"
 '!	"Negates value"
 '!=	"Not equal operator"
 '<>	"Not equal operator"
 'NOW	"Return the current date and time"
 'NULLIF	"Return NULL if expr1 = expr2"
 'NumGeometries	"Return number of geometries in geometry collection"
 'NumInteriorRings	"Return number of interior rings in Polygon"
 'NumPoints	"Return number of points in LineString"
 'OCT	"Return a string containing octal representation of a number"
 'OCTET_LENGTH	"Synonym for LENGTH"
 'OLD_PASSWORD	"Return the value of the pre-4.1 implementation of PASSWORD"
 '||	"Logical OR"
 'OR	"Logical OR"
 'ORD	"Return character code for leftmost character of the argument"
 'Overlaps	"Whether MBRs of two geometries overlap"
 'PASSWORD	"Calculate and return a password string"
 'PERIOD_ADD	"Add a period to a year-month"
 'PERIOD_DIFF	"Return the number of months between periods"
 'PI	"Return the value of pi"
 '+	"Addition operator"
 'Point	"Construct Point from coordinates"
 'PointFromText	"Construct Point from WKT"
 'PointFromWKB	"Construct Point from WKB"
 'PointN	"Return N-th point from LineString"
 'PolyFromText	"Construct Polygon from WKT"
 'PolygonFromText	"Construct Polygon from WKT"
 'PolyFromWKB	"Construct Polygon from WKB"
 'PolygonFromWKB	"Construct Polygon from WKB"
 'Polygon	"Construct Polygon from LineString arguments"
 'POSITION	"Synonym for LOCATE"
 'POW	"Return the argument raised to the specified power"
 'POWER	"Return the argument raised to the specified power"
 'ANALYSE	"Analyze the results of a query"
 'QUARTER	"Return the quarter from a date argument"
 'QUOTE	"Escape the argument for use in an SQL statement"
 'RADIANS	"Return argument converted to radians"
 'RAND	"Return a random floating-point value"
 'REGEXP	"Whether string matches regular expression"
 'RELEASE_LOCK	"Releases the named lock"
 'REPEAT	"Repeat a string the specified number of times"
 'REPLACE	"Replace occurrences of a specified string"
 'REVERSE	"Reverse the characters in a string"
 'RIGHT	"Return the specified rightmost number of characters"
 '>>	"Right shift"
 'RLIKE	"Whether string matches regular expression"
 'ROUND	"Round the argument"
 'ROW_COUNT	"The number of rows updated"
 'RPAD	"Append string the specified number of times"
 'RTRIM	"Remove trailing spaces"
 'SCHEMA	"Synonym for DATABASE"
 'SEC_TO_TIME	"Converts seconds to 'HH:MM:SS' format"
 'SECOND	"Return the second (0-59)"
 'SESSION_USER	"Synonym for USER"
 'SHA1	"Calculate an SHA-1 160-bit checksum"
 'SHA	"Calculate an SHA-1 160-bit checksum"
 'SHA2	"Calculate an SHA-2 checksum"
 'SIGN	"Return the sign of the argument"
 'SIN	"Return the sine of the argument"
 'SLEEP	"Sleep for a number of seconds"
 'SOUNDEX	"Return a soundex string"
 'SOUNDS	"Compare sounds"
 'SPACE	"Return a string of the specified number of spaces"
 'SQRT	"Return the square root of the argument"
 'SRID	"Return spatial reference system ID for geometry"
 'StartPoint	"Start Point of LineString"
 'STD	"Return the population standard deviation"
 'STDDEV	"Return the population standard deviation"
 'STDDEV_POP	"Return the population standard deviation"
 'STDDEV_SAMP	"Return the sample standard deviation"
 'STR_TO_DATE	"Convert a string to a date"
 'STRCMP	"Compare two strings"
 'SUBDATE	"Synonym for DATE_SUB when invoked with three arguments"
 'SUBSTR	"Return the substring as specified"
 'SUBSTRING	"Return the substring as specified"
 'SUBSTRING_INDEX	"Return a substring from a string before the specified number of occurrences of the delimiter"
 'SUBTIME	"Subtract times"
 'SUM	"Return the sum"
 'SYSDATE	"Return the time at which the function executes"
 'SYSTEM_USER	"Synonym for USER"
 'TAN	"Return the tangent of the argument"
 'TIME	"Extract the time portion of the expression passed"
 'TIME_FORMAT	"Format as time"
 'TIME_TO_SEC	"Return the argument converted to seconds"
 'TIMEDIFF	"Subtract time"
 '*	"Multiplication operator"
 'TIMESTAMP	"With a single argument, this function returns the date or datetime expression; with two arguments, the sum of the arguments"
 'TIMESTAMPADD	"Add an interval to a datetime expression"
 'TIMESTAMPDIFF	"Subtract an interval from a datetime expression"
 'TO_DAYS	"Return the date argument converted to days"
 'TO_SECONDS	"Return the date or datetime argument converted to seconds since Year 0"
 'Touches	"Whether one geometry touches another"
 'TRIM	"Remove leading and trailing spaces"
 'TRUNCATE	"Truncate to specified number of decimal places"
 'UCASE	"Synonym for UPPER"
 '-	"Change the sign of the argument"
 'UNCOMPRESS	"Uncompress a string compressed"
 'UNCOMPRESSED_LENGTH	"Return the length of a string before compression"
 'UNHEX	"Return a string containing hex representation of a number"
 'UNIX_TIMESTAMP	"Return a Unix timestamp"
 'UpdateXML	"Return replaced XML fragment"
 'UPPER	"Convert to uppercase"
 'USER	"The user name and host name provided by the client"
 'UTC_DATE	"Return the current UTC date"
 'UTC_TIME	"Return the current UTC time"
 'UTC_TIMESTAMP	"Return the current UTC date and time"
 'UUID	"Return a Universal Unique Identifier (UUID)"
 'UUID_SHORT	"Return an integer-valued universal identifier"
 'VALUES	"Defines the values to be used during an INSERT"
 'VAR_POP	"Return the population standard variance"
 'VAR_SAMP	"Return the sample variance"
 'VARIANCE	"Return the population standard variance"
 'VERSION	"Return a string that indicates the MySQL server version"
 'WEEK	"Return the week number"
 'WEEKDAY	"Return the weekday index"
 'WEEKOFYEAR	"Return the calendar week of the date (1-53)"
 'Within	"Whether MBR of one geometry is within MBR of another"
 'X	"Return X coordinate of Point"
 'XOR	"Logical XOR"
 'Y	"Return Y coordinate of Point"
 'YEAR	"Return the year"
 'YEARWEEK	"Return the year and week")

(provide 'ejc-keywords)
